### PR TITLE
fix: PDF generation

### LINKED ISSUE #83: fix: correctly query customer address
I noticed the pdf was putting in my address, instead of the customers address. I'm not sure if it is just pulling from the wrong thing or if that was on purpose 
To clarify the "Owner" refers to the owner of the field. Or rather the customers address. My bad.

### PR DESCRIPTION
**Pull request by Pertempto**
Resolves #83 #81
## Changes
Improved PDF generation logic
- Correctly fetch customer
- Remove dangerous characters from paths
- Removed logic to delete old file - it was causing errors on my system for some files

### CODE REVIEW

File: app/lib/pdf_generator.dart [hunk 1]
```diff
@@ -100,16 +100,13 @@ class PDFGenerator {
...
+            // Remove all dangerous characters
+            .replaceAll(RegExp(r'[^\w-_]'), '');
 
     final outputFilePath = path.join(directoryPath, fileName);
     final outputFile = File(outputFilePath);
 
-    // Ensure the old file is deleted before writing the new one
-    if (await outputFile.exists()) {
-      await outputFile.delete();
-    }
```
Comment (Pertempto) [inline app/lib/pdf_generator.dart:111]: We actually didn't even need this. The file is correctly overwritten if I am careful to close my PDF viewer.

File: app/lib/pdf_generator.dart [hunk 2]
```diff
@@ -14,7 +14,7 @@ class PDFGenerator {
   Future<void> generateAndSavePDF(Record recordData) async {
     final document = pdf.Document();
     final applicator = await ApplicatorDao().get(recordData.applicatorId);
-    final customer = await CustomerDao().get(recordData.applicatorId);
+    final customer = await CustomerDao().get(recordData.customerId);
```
Comment (Pertempto) [inline app/lib/pdf_generator.dart:17]: Haha we both missed this 🤦🏽

File: app/lib/pdf_generator.dart [hunk 3]
```diff
@@ -100,16 +100,13 @@ class PDFGenerator {
     final directoryPath = '/storage/emulated/0/Download';
     final fileName =
         '${applicator?.name ?? 'Unknown Applicator'} ${recordData.fieldName} ${formattedDate}_$formattedTime.pdf'
-            .replaceAll(' ', '_');
+            .replaceAll(' ', '_')
+            // Remove all dangerous characters
+            .replaceAll(RegExp(r'[^\w-_]'), '');
```
Comment (Pertempto) [inline app/lib/pdf_generator.dart:105]:
```suggestion
            .replaceAll(RegExp(r'[^\w\-_]'), '');

```

**Review by JCampana98 — APPROVED** [review]
